const Fila1 = ['Esc', 'F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8', 'F9', 'F10', 'F11', 'F12', 'Impr', 'Bloq Despl', 'Paus']
const Fila1 = ['°', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '?', '¡', '<-', 'Insert', 'Inicio', 'Re Pág', 'Bloq Num', '/', '*', '-']
const Fila1 = ['Tab', 'Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P', '´', '+', 'Enter', 'Supr', 'Fin', 'Av Pág', '7', '8', '9', '+']
const Fila1 = ['Mayus', 'A', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L', 'Ñ', '{', '}', '4', '5', '6']
const Fila1 = ['Shift', '<', 'Z', 'X', 'C', 'V', 'B', 'N', 'M', ',', '.', '-', 'Shift', '⬆', '1', '2', '3', 'Intro']
const Fila1 = ['Ctrl', 'Windows', 'Alt', 'Espacio', 'Alt Gr', 'FN', '🖱', 'Ctrl', '⬅', '⬇', '➡', '0', '.']